app_name: rs-api
app_debug: true
app_port: 1338
redis_conf:
    dsn: "redis://:@127.0.0.1:6379/0"
    max_size: 200
    min_idle: 10
    max_lifetime: 1800 # 单位s
    idle_timeout: 300 # 单位s
    connection_timeout: 10 #单位s
