[package]
name = "rs-api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "job"
path = "src/job.rs"

[dependencies]
axum = "0.6.18"
tower = "0.4.13"
tokio = { version = "1.28.0", features = ["full"] }
serde = { version = "1.0.162", features = ["derive"] }
serde_json = "1.0.96"
serde_yaml = "0.9.21"
once_cell = "1.17.1"
rs_infras = "0.1.5"

# redis crates
redis = { version ="0.23.0",features = ["r2d2","tokio-comp","cluster","json"]}
r2d2 = "0.8.10"

#uuid
uuid = { version = "0.8.2", features = ["serde", "v4"] }

#validator
validator = { version = "0.16.0", features = ["derive"] }
async-trait = "0.1.68"
thiserror = "1.0.40"
